name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  build-dazl:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy env file
        run: cp .env.example .env
      - name: Install deps
        run: composer install 
     
      - name: Generate App Key
        run: php artisan key:generate --force
 #     - name: Run New Migrations
 #       run: php artisan migrate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
